parent: classic
name: child_classic
display_name: Child theme of classic's theme
version: 1.0.0
author:
  name: "Pl Jo"
  email: "admin@theeyeug.com"
  url: "https://theeyeug.com"
assets:
  use_parent_assets: false
